// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for android - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCCpuDL6o9dAjbd31lk2_8RsW_3HCmAqoE',
    appId: '1:1066074368580:web:e09abec5316a223ef76a11',
    messagingSenderId: '1066074368580',
    projectId: 'project-yukki',
    authDomain: 'project-yukki.firebaseapp.com',
    storageBucket: 'project-yukki.appspot.com',
    measurementId: 'G-S2BHPV739Q',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBMdE3pWEzVMI0A96hb1pC3oHleFloVhXs',
    appId: '1:1066074368580:ios:37a42192e3ead81ff76a11',
    messagingSenderId: '1066074368580',
    projectId: 'project-yukki',
    storageBucket: 'project-yukki.appspot.com',
    iosClientId: '1066074368580-adjvlj9i5iecbo74ke5crv7cf4p96027.apps.googleusercontent.com',
    iosBundleId: 'app.yukki.engine',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCCpuDL6o9dAjbd31lk2_8RsW_3HCmAqoE',
    appId: '1:1066074368580:web:88eca83459d57326f76a11',
    messagingSenderId: '1066074368580',
    projectId: 'project-yukki',
    authDomain: 'project-yukki.firebaseapp.com',
    storageBucket: 'project-yukki.appspot.com',
    measurementId: 'G-0P8D8WCVN0',
  );
}
